-- Table pour les FLOTs (transferts d'argent entre shops)
CREATE TABLE IF NOT EXISTS `flots` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `shop_source_id` INT(11) NOT NULL,
  `shop_destination_id` INT(11) NOT NULL,
  `montant` DECIMAL(15,2) NOT NULL,
  `devise` VARCHAR(10) DEFAULT 'USD',
  `mode_paiement` ENUM('cash', 'airtelMoney', 'mPesa', 'orangeMoney') NOT NULL DEFAULT 'cash',
  `statut` ENUM('enRoute', 'servi', 'annule') NOT NULL DEFAULT 'enRoute',
  `agent_envoyeur_id` INT(11) NOT NULL,
  `agent_recepteur_id` INT(11) DEFAULT NULL,
  `date_envoi` DATETIME NOT NULL,
  `date_reception` DATETIME DEFAULT NULL,
  `reference` VARCHAR(100) DEFAULT NULL,
  `notes` TEXT DEFAULT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `last_modified_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `last_modified_by` VARCHAR(100) DEFAULT NULL,
  `is_synced` TINYINT(1) DEFAULT 0,
  `synced_at` DATETIME DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_shop_source` (`shop_source_id`),
  KEY `idx_shop_destination` (`shop_destination_id`),
  KEY `idx_statut` (`statut`),
  KEY `idx_date_envoi` (`date_envoi`),
  KEY `idx_agent_envoyeur` (`agent_envoyeur_id`),
  KEY `idx_agent_recepteur` (`agent_recepteur_id`),
  KEY `idx_reference` (`reference`),
  KEY `idx_last_modified` (`last_modified_at`),
  CONSTRAINT `fk_flot_shop_source` FOREIGN KEY (`shop_source_id`) REFERENCES `shops` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_flot_shop_destination` FOREIGN KEY (`shop_destination_id`) REFERENCES `shops` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_flot_agent_envoyeur` FOREIGN KEY (`agent_envoyeur_id`) REFERENCES `agents` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_flot_agent_recepteur` FOREIGN KEY (`agent_recepteur_id`) REFERENCES `agents` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
